services:
  - type: web
    name: wiki-project  # Change this to your preferred name
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn wiki:app"